#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=01:00:00
#PBS -l vmem=28gb
#PBS -N generate-cortexmap-images

set -x
set -e

surface=`jq -r '.surface' config.json`

# convert surfaces
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

if [[ ${surface} == 'midthickness']]; then
  time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 ./convert-surfaces.sh
fi

# generate images
time singularity exec -e docker://brainlife/pysurfer:0.10.0 ./generate-images.py

# clean up
rm -rf cortexmap output
