#!/bin/bash
#PBS -l nodes=1:ppn=4,walltime=01:00:00
#PBS -l vmem=20gb
#PBS -N generate-tract-endpoint-images

set -x
set -e

# convert surfaces
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./convert_to_surface.sh

# generate images
time singularity exec -e docker://brainlife/pysurfer:0.10.0 ./create-images.py

# clean up
rm -rf cortexmap output
